#!/bin/bash

########## PLAY STARTUP SOUND #########
#sound

sh /usr/local/bin/auto-icewm-menu.sh & # Update the menu

#killall icewmtray
#icewmtray &
#sleep 2 && wicd-client &

# xgamma -rgamma 1.3 -ggamma 1.3 -bgamma 1.3 # Uncomment this line if you need gamma correction.
# Go to http://links.twibright.com/calibration.html to adjust your gamma.

rox --pinboard=swift ## Activate ROX pinboard to showdesktop icons


conky & # Activate Conky display
